# Generated by Django 2.2.3 on 2019-07-27 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Checkproblem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkwhen', models.DateField()),
                ('checkdepartment', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('checkway', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('checkwho', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('problemdetail', models.CharField(blank=True, default='', max_length=3000, null=True)),
                ('problemtype', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('problemsolve', models.CharField(blank=True, default='', max_length=3000, null=True)),
                ('whoresponsible', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('departmentincharge', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('problemdepartment', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('departmentwho', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('problemteam', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('problemwho', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('problemreason', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('closedate', models.DateField(blank=True, null=True)),
                ('ifdone', models.BooleanField(blank=True, default=False, null=True)),
                ('projecttype', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('closewho', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('somethingelse', models.CharField(blank=True, default='', max_length=3000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inquireproblem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkwhenstart', models.DateField(blank=True, null=True)),
                ('checkwhenend', models.DateField(blank=True, null=True)),
                ('checkdepartment', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('checkway', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('checkwho', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('problemdetail', models.CharField(blank=True, default='', max_length=3000, null=True)),
                ('problemtype', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('problemsolve', models.CharField(blank=True, default='', max_length=3000, null=True)),
                ('whoresponsible', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('departmentincharge', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('problemdepartment', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('departmentwho', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('problemteam', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('problemwho', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('problemreason', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('closedate', models.DateField(blank=True, null=True)),
                ('ifdone', models.BooleanField(blank=True, default=False, null=True)),
                ('projecttype', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('closewho', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('somethingelse', models.CharField(blank=True, default='', max_length=3000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImgProblem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='media')),
                ('Checkproblem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checksource.Checkproblem')),
            ],
        ),
    ]
